//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fragment_Launcher {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class info : global::System.Configuration.ApplicationSettingsBase {
        
        private static info defaultInstance = ((info)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new info())));
        
        public static info Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string isoFilePath {
            get {
                return ((string)(this["isoFilePath"]));
            }
            set {
                this["isoFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastCheck {
            get {
                return ((string)(this["lastCheck"]));
            }
            set {
                this["lastCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string telliFolder {
            get {
                return ((string)(this["telliFolder"]));
            }
            set {
                this["telliFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pcsx2Folder {
            get {
                return ((string)(this["pcsx2Folder"]));
            }
            set {
                this["pcsx2Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string viGithubVersion {
            get {
                return ((string)(this["viGithubVersion"]));
            }
            set {
                this["viGithubVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v0.0.0")]
        public string aliceGithubVersion {
            get {
                return ((string)(this["aliceGithubVersion"]));
            }
            set {
                this["aliceGithubVersion"] = value;
            }
        }
    }
}
